-- Correr en system
CREATE TABLESPACE VET_PROYECTO
DATAFILE 'E:\Databases\Produccion\vet_proyecto_01.dbf'
SIZE 100M 
AUTOEXTEND ON 
NEXT 10M 
MAXSIZE UNLIMITED;

CREATE PROFILE Perfil_LECTURA LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 90
    IDLE_TIME 30;

CREATE PROFILE Perfil_Admin LIMIT
    FAILED_LOGIN_ATTEMPTS UNLIMITED
    PASSWORD_LIFE_TIME UNLIMITED
    IDLE_TIME UNLIMITED;

CREATE ROLE Rol_Lectura;
GRANT CREATE SESSION TO ROL_LECTURA;
CREATE ROLE Rol_Veterinario;
GRANT CREATE SESSION TO ROL_VETERINARIO;
CREATE ROLE Rol_Admin;
GRANT RESOURCE, CONNECT TO Rol_Admin;

CREATE USER Admin_Vet IDENTIFIED BY Pa$$word
DEFAULT TABLESPACE VET_PROYECTO
QUOTA UNLIMITED ON VET_PROYECTO;
GRANT Rol_Admin TO Admin_Vet;
ALTER USER Admin_Vet PROFILE Perfil_Admin;

CREATE USER User_Vet IDENTIFIED BY Pa$$word
DEFAULT TABLESPACE VET_PROYECTO
QUOTA 10M ON VET_PROYECTO;
GRANT Rol_Veterinario TO User_Vet;
ALTER USER User_Vet PROFILE Perfil_Admin;

CREATE USER Recepcionista_Vet IDENTIFIED BY Pa$$word
DEFAULT TABLESPACE VET_PROYECTO
QUOTA 5M ON VET_PROYECTO;
GRANT Rol_Lectura TO Recepcionista_Vet;
ALTER USER Recepcionista_Vet PROFILE Perfil_LECTURA;	