--Correr es System

CREATE USER Respaldo_Vet IDENTIFIED BY "Pa$$word"
DEFAULT TABLESPACE VET_PROYECTO
QUOTA UNLIMITED ON VET_PROYECTO;
GRANT Rol_Veterinario TO Respaldo_Vet;
ALTER USER Respaldo_Vet PROFILE PERFIL_RESPALDO_ADMIN;

CREATE PROFILE PERFIL_RESPALDO_ADMIN LIMIT
    FAILED_LOGIN_ATTEMPTS UNLIMITED
    PASSWORD_LIFE_TIME UNLIMITED
    IDLE_TIME UNLIMITED
    SESSIONS_PER_USER UNLIMITED;

-Correr en Admin_Vet

CREATE MATERIALIZED VIEW MV_TODAS_CITAS
REFRESH COMPLETE ON DEMAND
AS
SELECT 
    c.ID_CITA,
    c.FECHA_CITA,
    c.HORA,
    m.NOMBRE as MASCOTA_NOMBRE,
    cl.NOMBRE as CLIENTE_NOMBRE,
    v.NOMBRE as VETERINARIO_NOMBRE,
    s.NOMBRE as SERVICIO_NOMBRE,
    s.PRECIO
FROM CITA c
JOIN MASCOTA m ON c.FK_MASCOTA = m.ID_MASCOTA
JOIN CLIENTE cl ON m.FK_CLIENTE = cl.ID_CLIENTE
JOIN VETERINARIO v ON c.FK_VETERINARIO = v.ID_VETERINARIO
JOIN SERVICIO s ON c.FK_SERVICIO = s.ID_SERVICIO;

SELECT * FROM MV_TODAS_CITAS 
WHERE TRUNC(FECHA_CITA) = DATE '2025-07-30';

CREATE MATERIALIZED VIEW ADMIN_VET.MV_PRODUCTOS_STOCK
REFRESH COMPLETE ON DEMAND
AS
SELECT 
    p.NOMBRE_PRODUCTO,
    p.DESCRIPCION,
    i.CANTIDAD,
    i.PRECIO_U as PRECIO_UNITARIO,
    CASE 
        WHEN i.INSTOCK = 1 THEN 'DISPONIBLE'
        WHEN i.INSTOCK = 0 THEN 'AGOTADO'
        ELSE 'DESCONOCIDO'
    END as ESTADO_STOCK
FROM ADMIN_VET.PRODUCTO p
JOIN ADMIN_VET.INVENTARIO i ON p.FK_STOCK = i.ID_STOCK
WHERE i.INSTOCK = 1;

SELECT * FROM ADMIN_VET.MV_PRODUCTOS_STOCK;

CREATE TABLE MASCOTA_COMPLETA (
    ID_MASCOTA NUMBER PRIMARY KEY,
    NOMBRE_MASCOTA VARCHAR2(100),
    ESPECIE VARCHAR2(50),
    RAZA VARCHAR2(50),
    EDAD NUMBER,
    PESO NUMBER(5,2),
    NOTAS_MASCOTA CLOB,
    ID_CLIENTE NUMBER NOT NULL,
    NOMBRE_CLIENTE VARCHAR2(100),
    APELLIDO_CLIENTE VARCHAR2(100),
    EMAIL VARCHAR2(150),
    TELEFONO VARCHAR2(20),
    FK_DIRECCION_CLIENTE NUMBER,
    ID_HISTORIAL NUMBER NOT NULL,
    FECHA_HISTORIAL DATE,
    OBSERVACIONES_HISTORIAL CLOB,
    FK_VETERINARIO NUMBER,
    FK_PROCEDIMIENTO NUMBER,
    FK_DIRECCION_VETERINARIO NUMBER,
    FK_CITA NUMBER,
    
    NOMBRE_COMPLETO_CLIENTE VARCHAR2(201) GENERATED ALWAYS AS (NOMBRE_CLIENTE || ' ' || APELLIDO_CLIENTE) VIRTUAL,
    DESCRIPCION_MASCOTA VARCHAR2(206) GENERATED ALWAYS AS (NOMBRE_MASCOTA || ' - ' || ESPECIE || ' (' || RAZA || ')') VIRTUAL,
    
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT SYSTIMESTAMP
);

INSERT INTO MASCOTA_COMPLETA (
    ID_MASCOTA,
    NOMBRE_MASCOTA,
    ESPECIE,
    RAZA,
    EDAD,
    PESO,
    NOTAS_MASCOTA,
    ID_CLIENTE,
    NOMBRE_CLIENTE,
    APELLIDO_CLIENTE,
    EMAIL,
    TELEFONO,
    FK_DIRECCION_CLIENTE,
    ID_HISTORIAL,
    FECHA_HISTORIAL,
    OBSERVACIONES_HISTORIAL,
    FK_VETERINARIO,
    FK_PROCEDIMIENTO,
    FK_DIRECCION_VETERINARIO,
    FK_CITA
)
SELECT 
    m.ID_MASCOTA,
    m.NOMBRE,
    m.ESPECIE,
    m.RAZA,
    m.EDAD,
    m.PESO,
    m.NOTAS,
    c.ID_CLIENTE,
    c.NOMBRE,
    c.APELLIDO,
    c.EMAIL,
    c.TELEFONO,
    c.FK_DIRECCION,
    hm.ID_HISTORIAL,
    hm.FECHA,
    hm.OBSERVACIONES,
    hm.FK_VETERINARIO,
    hm.FK_PROCEDIMIENTO,
    v.FK_DIRECCION,
    NULL
FROM MASCOTA m
INNER JOIN CLIENTE c ON m.FK_CLIENTE = c.ID_CLIENTE
LEFT JOIN HISTORIAL_MEDICO hm ON m.ID_MASCOTA = hm.FK_MASCOTA
LEFT JOIN VETERINARIO v ON hm.FK_VETERINARIO = v.ID_VETERINARIO
WHERE hm.FECHA = (SELECT MAX(FECHA) FROM HISTORIAL_MEDICO hm2 
                  WHERE hm2.FK_MASCOTA = m.ID_MASCOTA)
   OR hm.ID_HISTORIAL IS NULL;
