CREATE TABLESPACE VET_PROYECTO
DATAFILE 'E:\Databases\Produccion\vet_proyecto_01.dbf'
SIZE 100M 
AUTOEXTEND ON 
NEXT 10M 
MAXSIZE UNLIMITED;

CREATE PROFILE Perfil_LECTURA LIMIT
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 90
    IDLE_TIME 30;

CREATE PROFILE Perfil_Admin LIMIT
    FAILED_LOGIN_ATTEMPTS UNLIMITED
    PASSWORD_LIFE_TIME UNLIMITED
    IDLE_TIME UNLIMITED;

CREATE ROLE Rol_Lectura;
GRANT CREATE SESSION TO ROL_LECTURA;

CREATE ROLE Rol_Veterinario;
GRANT CREATE SESSION TO ROL_VETERINARIO;

CREATE ROLE Rol_Admin;
GRANT RESOURCE, CONNECT TO Rol_Admin;

CREATE USER Admin_Vet IDENTIFIED BY Pa$$word
DEFAULT TABLESPACE VET_PROYECTO
QUOTA UNLIMITED ON VET_PROYECTO;
GRANT Rol_Admin TO Admin_Vet;
ALTER USER Admin_Vet PROFILE Perfil_Admin;

CREATE USER User_Vet IDENTIFIED BY Pa$$word
DEFAULT TABLESPACE VET_PROYECTO
QUOTA 10M ON VET_PROYECTO;
GRANT Rol_Veterinario TO User_Vet;
ALTER USER User_Vet PROFILE Perfil_Admin;

CREATE USER Recepcionista_Vet IDENTIFIED BY Pa$$word
DEFAULT TABLESPACE VET_PROYECTO
QUOTA 5M ON VET_PROYECTO;
GRANT Rol_Lectura TO Recepcionista_Vet;
ALTER USER Recepcionista_Vet PROFILE Perfil_LECTURA;

-- Conectado como Admin_Vet:

CREATE TABLE Direccion(
    ID_Direccion NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    Provincia VARCHAR2(100) NOT NULL, Canton VARCHAR2(100) NOT NULL, Distrito VARCHAR2(100) NOT NULL,
    Direccion_Detalle VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_Direccion PRIMARY KEY (ID_Direccion)
) TABLESPACE VET_PROYECTO;

CREATE TABLE Servicio(
    ID_Servicio NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    Nombre VARCHAR2(100) NOT NULL, Descripcion VARCHAR2(255), Precio NUMBER(10, 2) NOT NULL,
    CONSTRAINT PK_Servicio PRIMARY KEY (ID_Servicio),
    CONSTRAINT CHK_Servicio_Precio CHECK (Precio > 0)
) TABLESPACE VET_PROYECTO;

CREATE TABLE Procedimiento(
    ID_Procedimiento NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    Nombre VARCHAR2(100) NOT NULL, Descripcion VARCHAR2(255), Costo NUMBER(10, 2) NOT NULL,
    CONSTRAINT PK_Procedimiento PRIMARY KEY (ID_Procedimiento)
) TABLESPACE VET_PROYECTO;

CREATE TABLE Inventario(
    ID_Stock NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    InStock NUMBER(1) NOT NULL, Precio_U NUMBER(10, 2) NOT NULL, Cantidad NUMBER NOT NULL,
    CONSTRAINT PK_Inventario PRIMARY KEY (ID_Stock),
    CONSTRAINT CHK_Inventario_Cantidad CHECK (Cantidad >= 0)
) TABLESPACE VET_PROYECTO;

CREATE TABLE Cliente(
    ID_Cliente NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    Nombre VARCHAR2(100) NOT NULL, Apellido VARCHAR2(100) NOT NULL, Email VARCHAR2(100) NOT NULL,
    Telefono VARCHAR2(15) NOT NULL, Fk_Direccion NUMBER NOT NULL,
    CONSTRAINT PK_Cliente PRIMARY KEY (ID_Cliente),
    CONSTRAINT UK_Cliente_Email UNIQUE (Email)
) TABLESPACE VET_PROYECTO;

CREATE TABLE Veterinario(
    ID_Veterinario NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    Nombre VARCHAR2(100) NOT NULL, Apellido VARCHAR2(100) NOT NULL, Licencia VARCHAR2(20) NOT NULL,
    Email VARCHAR2(100) NOT NULL, Telefono VARCHAR2(15) NOT NULL, Fk_Direccion NUMBER NOT NULL,
    CONSTRAINT PK_Veterinario PRIMARY KEY (ID_Veterinario),
    CONSTRAINT UK_Veterinario_Licencia UNIQUE (Licencia)
) TABLESPACE VET_PROYECTO;

CREATE TABLE Mascota(
    ID_Mascota NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    Nombre VARCHAR2(100) NOT NULL, Especie VARCHAR2(50) NOT NULL, Raza VARCHAR2(100),
    Fk_Cliente NUMBER NOT NULL, Edad NUMBER NOT NULL, Peso NUMBER(5, 2) NOT NULL, Notas VARCHAR2(255),
    CONSTRAINT PK_Mascota PRIMARY KEY (ID_Mascota),
    CONSTRAINT CHK_Mascota_Edad CHECK (Edad >= 0)
) TABLESPACE VET_PROYECTO;

CREATE TABLE Producto(
    ID_Producto NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    Nombre_Producto VARCHAR2(100) NOT NULL, Descripcion VARCHAR2(255), Fk_Stock NUMBER NOT NULL,
    CONSTRAINT PK_Producto PRIMARY KEY (ID_Producto)
) TABLESPACE VET_PROYECTO;

CREATE TABLE Factura(
    ID_Factura NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    Fk_Cliente NUMBER NOT NULL, Total NUMBER(10, 2) NOT NULL, Fecha_Factura DATE NOT NULL,
    CONSTRAINT PK_Factura PRIMARY KEY (ID_Factura)
) TABLESPACE VET_PROYECTO;

CREATE TABLE Detalle_Factura(
    ID_DetalleFactura NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    Fk_Factura NUMBER NOT NULL, Fk_Producto NUMBER, Fk_Servicio NUMBER,
    Precio_U NUMBER(10, 2) NOT NULL, Cantidad NUMBER NOT NULL, PrecioT NUMBER(10, 2) NOT NULL,
    CONSTRAINT PK_DetalleFactura PRIMARY KEY (ID_DetalleFactura),
    CONSTRAINT CHK_Detalle_XOR CHECK ((Fk_Producto IS NOT NULL AND Fk_Servicio IS NULL) OR (Fk_Producto IS NULL AND Fk_Servicio IS NOT NULL))
) TABLESPACE VET_PROYECTO;

CREATE TABLE Cita(
    ID_Cita NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    Fk_Mascota NUMBER NOT NULL, Fk_Veterinario NUMBER NOT NULL, Fk_Servicio NUMBER NOT NULL,
    Fecha_Cita DATE NOT NULL, Hora VARCHAR2(5) NOT NULL,
    CONSTRAINT PK_Cita PRIMARY KEY (ID_Cita),
    CONSTRAINT CHK_Cita_Hora CHECK (REGEXP_LIKE(Hora, '^[0-2][0-9]:[0-5][0-9]$'))
) TABLESPACE VET_PROYECTO;

CREATE TABLE Historial_Medico(
    ID_Historial NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    Fk_Mascota NUMBER NOT NULL, Fk_Veterinario NUMBER NOT NULL, Fk_Procedimiento NUMBER,
    Fecha DATE NOT NULL, Observaciones VARCHAR2(500) NOT NULL,
    CONSTRAINT PK_Historial PRIMARY KEY (ID_Historial)
) TABLESPACE VET_PROYECTO;

-- ROL_LECTURA: solo puede ver datos
GRANT SELECT ON Cliente TO Rol_Lectura;
GRANT SELECT ON Mascota TO Rol_Lectura;

-- ROL_VETERINARIO: puede ver y modificar sus datos
GRANT SELECT, INSERT, UPDATE, DELETE ON Cita TO Rol_Veterinario;
GRANT SELECT ON Cliente TO Rol_Veterinario;